# LiveGPT
#
# The following env variables must be set:
# GOOGLE_APPLICATION_CREDENTIALS musts be set to use the TTS & STT
# OPENAI_API_KEY musts be set to use the ChatCompletion

development: true
logging:
  json: false
  level: debug



port: 3001
